// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.24.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-posts.ts
var list_posts_default = defineTool({
  name: "list_posts",
  title: "List posts",
  description: "List blog posts with optional filters. Returns id, title, slug, category, date, excerpt, and published status.",
  inputSchema: {
    category: z.enum(["CS Projects", "Math Olympiad", "NBA Analysis"]).optional().describe("Filter by category."),
    published_only: z.boolean().optional().default(false).describe("Only return published posts."),
    limit: z.number().int().min(1).max(100).optional().default(50).describe("Maximum posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, published_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("posts").select("id, title, slug, category, date, excerpt, published").order("date", { ascending: false });
    if (category) q = q.eq("category", category);
    if (published_only) q = q.eq("published", true);
    q = q.limit(limit);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }] };
  }
});

// src/lib/mcp/tools/get-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.24.2";
var get_post_default = defineTool2({
  name: "get_post",
  title: "Get post",
  description: "Fetch a single blog post by slug, including its full body and metadata.",
  inputSchema: {
    slug: z2.string().min(1).describe("URL slug of the post.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("posts").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `Post "${slug}" not found.` }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  }
});

// src/lib/mcp/tools/create-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.24.2";
var create_post_default = defineTool3({
  name: "create_post",
  title: "Create post",
  description: "Create a new blog post. The current date is used unless overridden. Slug is auto-generated from the title if omitted.",
  inputSchema: {
    title: z3.string().min(1).describe("Post title."),
    slug: z3.string().min(1).optional().describe("URL-safe slug; auto-generated from title if not provided."),
    category: z3.enum(["CS Projects", "Math Olympiad", "NBA Analysis"]).describe("Post category."),
    body: z3.string().default("").describe("Full post body in Markdown/LaTeX."),
    excerpt: z3.string().default("").describe("Short preview excerpt."),
    tags: z3.array(z3.string()).default([]).describe("List of tags."),
    cover_image: z3.string().url().optional().describe("URL to a cover image."),
    published: z3.boolean().default(false).describe("Whether the post is publicly visible."),
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Publication date in YYYY-MM-DD; defaults to today.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const date = input.date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const slug = input.slug ?? input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const { data, error } = await supabase.from("posts").insert({
      title: input.title,
      slug,
      category: input.category,
      body: input.body,
      excerpt: input.excerpt,
      tags: input.tags,
      cover_image: input.cover_image ?? null,
      published: input.published,
      date,
      sort_order: 0
    }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created post "${input.title}" at slug "${slug}".
${JSON.stringify(data?.[0] ?? {}, null, 2)}` }] };
  }
});

// src/lib/mcp/tools/update-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.24.2";
var update_post_default = defineTool4({
  name: "update_post",
  title: "Update post",
  description: "Update an existing blog post by slug. Only provided fields are changed.",
  inputSchema: {
    slug: z4.string().min(1).describe("Slug of the post to update."),
    title: z4.string().min(1).optional().describe("New title."),
    category: z4.enum(["CS Projects", "Math Olympiad", "NBA Analysis"]).optional().describe("New category."),
    body: z4.string().optional().describe("New body."),
    excerpt: z4.string().optional().describe("New excerpt."),
    tags: z4.array(z4.string()).optional().describe("New list of tags."),
    cover_image: z4.string().url().optional().describe("New cover image URL."),
    published: z4.boolean().optional().describe("New published status.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { slug, ...updates } = input;
    const payload = {};
    for (const [k, v] of Object.entries(updates)) {
      if (v !== void 0) payload[k] = v;
    }
    if (Object.keys(payload).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const { data, error } = await supabase.from("posts").update(payload).eq("slug", slug).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) return { content: [{ type: "text", text: `Post "${slug}" not found or not authorized.` }], isError: true };
    return { content: [{ type: "text", text: `Updated post "${slug}".
${JSON.stringify(data[0], null, 2)}` }] };
  }
});

// src/lib/mcp/tools/delete-post.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.24.2";
var delete_post_default = defineTool5({
  name: "delete_post",
  title: "Delete post",
  description: "Delete a blog post by slug.",
  inputSchema: {
    slug: z5.string().min(1).describe("Slug of the post to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("posts").delete().eq("slug", slug);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Deleted post "${slug}".` }] };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.24.2";
var list_journal_entries_default = defineTool6({
  name: "list_journal_entries",
  title: "List journal entries",
  description: "List math olympiad journal entries.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).optional().default(50).describe("Maximum entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("journal_entries").select("id, title, date, body").order("date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }] };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.24.2";
var create_journal_entry_default = defineTool7({
  name: "create_journal_entry",
  title: "Create journal entry",
  description: "Add a new entry to the math olympiad journal.",
  inputSchema: {
    title: z7.string().min(1).describe("Entry title."),
    body: z7.string().default("").describe("Entry body in Markdown/LaTeX."),
    date: z7.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD; defaults to today.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ title, body, date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const finalDate = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("journal_entries").insert({ title, body, date: finalDate, sort_order: 0 }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created journal entry "${title}".
${JSON.stringify(data?.[0] ?? {}, null, 2)}` }] };
  }
});

// src/lib/mcp/tools/list-questions.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.24.2";
var list_questions_default = defineTool8({
  name: "list_questions",
  title: "List questions",
  description: "List custom math problems / questions.",
  inputSchema: {
    limit: z8.number().int().min(1).max(100).optional().default(50).describe("Maximum questions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("math_questions").select("id, title, date, source, difficulty, body").order("date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }] };
  }
});

// src/lib/mcp/tools/create-question.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.24.2";
var create_question_default = defineTool9({
  name: "create_question",
  title: "Create question",
  description: "Add a new math problem to the questions bank.",
  inputSchema: {
    title: z9.string().min(1).describe("Problem title."),
    body: z9.string().default("").describe("Problem statement in Markdown/LaTeX."),
    source: z9.string().optional().describe("Source or contest origin."),
    difficulty: z9.string().optional().describe("Difficulty label."),
    date: z9.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date in YYYY-MM-DD; defaults to today.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ title, body, source, difficulty, date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const finalDate = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("math_questions").insert({ title, body, source: source ?? null, difficulty: difficulty ?? null, date: finalDate, sort_order: 0 }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created question "${title}".
${JSON.stringify(data?.[0] ?? {}, null, 2)}` }] };
  }
});

// src/lib/mcp/tools/get-site-stats.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_site_stats_default = defineTool10({
  name: "get_site_stats",
  title: "Get site stats",
  description: "Return total site views and total post likes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const [{ count: likes }, { data: stats }] = await Promise.all([
      supabase.from("post_likes").select("*", { count: "exact", head: true }),
      supabase.from("site_stats").select("count").eq("key", "total_views").maybeSingle()
    ]);
    const result = { total_views: stats?.count ?? 0, total_likes: likes ?? 0 };
    return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
  }
});

// src/lib/mcp/tools/update-page-content.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^3.24.2";
var update_page_content_default = defineTool11({
  name: "update_page_content",
  title: "Update page content",
  description: "Update a page content key (e.g. home hero text) to a new value.",
  inputSchema: {
    key: z10.string().min(1).describe("Page content key."),
    value: z10.string().describe("New value.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ key, value }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("page_content").upsert({ key, value }, { onConflict: "key" });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Updated page content key "${key}".` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aeabbuzfpetjqbjxtdvn";
var mcp_default = defineMcp({
  name: "invariant-thinking",
  title: "Invariant Thinking",
  version: "1.0.0",
  instructions: "MCP server for the Invariant Thinking blog. Tools let you read and manage blog posts, math journal entries, math questions, site stats, and editable page content. Mutations require the connecting user to be an admin of the blog.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_posts_default,
    get_post_default,
    create_post_default,
    update_post_default,
    delete_post_default,
    list_journal_entries_default,
    create_journal_entry_default,
    list_questions_default,
    create_question_default,
    get_site_stats_default,
    update_page_content_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
